# frontend~HEAD/docker-compose.yml
# version: '3.8'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=deepseek-r1:1.5b
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/chatdb
    depends_on:
      - ollama
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    #volumes:
    #  - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped

  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/local
    working_dir: /local
    entrypoint: >
      sh -c "docker-entrypoint.sh generate -i /local/openapi.yaml -g python -o /local/python-client"
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_data:
