# coding: utf-8

# flake8: noqa
"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.api_chat_post200_response import ApiChatPost200Response
from openapi_client.models.api_chat_post_request import ApiChatPostRequest
from openapi_client.models.api_documents_get200_response import ApiDocumentsGet200Response
from openapi_client.models.api_documents_get200_response_documents_inner import ApiDocumentsGet200ResponseDocumentsInner
from openapi_client.models.api_documents_post200_response import ApiDocumentsPost200Response
from openapi_client.models.api_documents_post_request import ApiDocumentsPostRequest
from openapi_client.models.api_embeddings_update_post200_response import ApiEmbeddingsUpdatePost200Response
from openapi_client.models.api_health_get200_response import ApiHealthGet200Response
