# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApiHealthGet200Response(BaseModel):
    """
    ApiHealthGet200Response
    """ # noqa: E501
    status: Optional[StrictStr] = None
    ollama: Optional[StrictStr] = None
    database: Optional[StrictStr] = None
    embeddings: Optional[StrictStr] = None
    data_counts: Optional[Dict[str, Any]] = None
    test_response: Optional[StrictStr] = None
    errors: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["status", "ollama", "database", "embeddings", "data_counts", "test_response", "errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiHealthGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiHealthGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "ollama": obj.get("ollama"),
            "database": obj.get("database"),
            "embeddings": obj.get("embeddings"),
            "data_counts": obj.get("data_counts"),
            "test_response": obj.get("test_response"),
            "errors": obj.get("errors")
        })
        return _obj


