# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_documents_get200_response import ApiDocumentsGet200Response

class TestApiDocumentsGet200Response(unittest.TestCase):
    """ApiDocumentsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDocumentsGet200Response:
        """Test ApiDocumentsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDocumentsGet200Response`
        """
        model = ApiDocumentsGet200Response()
        if include_optional:
            return ApiDocumentsGet200Response(
                documents = [
                    openapi_client.models._api_documents_get_200_response_documents_inner._api_documents_get_200_response_documents_inner(
                        id = 56, 
                        title = '', 
                        content = '', 
                        created_at = '', 
                        chunk_count = 56, 
                        embedding_count = 56, )
                    ]
            )
        else:
            return ApiDocumentsGet200Response(
        )
        """

    def testApiDocumentsGet200Response(self):
        """Test ApiDocumentsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
