# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_embeddings_update_post200_response import ApiEmbeddingsUpdatePost200Response

class TestApiEmbeddingsUpdatePost200Response(unittest.TestCase):
    """ApiEmbeddingsUpdatePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiEmbeddingsUpdatePost200Response:
        """Test ApiEmbeddingsUpdatePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiEmbeddingsUpdatePost200Response`
        """
        model = ApiEmbeddingsUpdatePost200Response()
        if include_optional:
            return ApiEmbeddingsUpdatePost200Response(
                message = '',
                total_chunks = 56,
                embedded_chunks = 56
            )
        else:
            return ApiEmbeddingsUpdatePost200Response(
        )
        """

    def testApiEmbeddingsUpdatePost200Response(self):
        """Test ApiEmbeddingsUpdatePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
