# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_health_get200_response import ApiHealthGet200Response

class TestApiHealthGet200Response(unittest.TestCase):
    """ApiHealthGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiHealthGet200Response:
        """Test ApiHealthGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiHealthGet200Response`
        """
        model = ApiHealthGet200Response()
        if include_optional:
            return ApiHealthGet200Response(
                status = '',
                ollama = '',
                database = '',
                embeddings = '',
                data_counts = None,
                test_response = '',
                errors = [
                    ''
                    ]
            )
        else:
            return ApiHealthGet200Response(
        )
        """

    def testApiHealthGet200Response(self):
        """Test ApiHealthGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
