# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_chat_post_request import ApiChatPostRequest

class TestApiChatPostRequest(unittest.TestCase):
    """ApiChatPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiChatPostRequest:
        """Test ApiChatPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiChatPostRequest`
        """
        model = ApiChatPostRequest()
        if include_optional:
            return ApiChatPostRequest(
                message = '',
                use_rag = True
            )
        else:
            return ApiChatPostRequest(
        )
        """

    def testApiChatPostRequest(self):
        """Test ApiChatPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
