# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_chat_post(self) -> None:
        """Test case for api_chat_post

        Chat with LLM
        """
        pass

    def test_api_documents_get(self) -> None:
        """Test case for api_documents_get

        List all documents
        """
        pass

    def test_api_documents_post(self) -> None:
        """Test case for api_documents_post

        Add a new document
        """
        pass

    def test_api_embeddings_update_post(self) -> None:
        """Test case for api_embeddings_update_post

        Update all embeddings
        """
        pass

    def test_api_health_get(self) -> None:
        """Test case for api_health_get

        Health check
        """
        pass


if __name__ == '__main__':
    unittest.main()
