# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_chat_post200_response import ApiChatPost200Response

class TestApiChatPost200Response(unittest.TestCase):
    """ApiChatPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiChatPost200Response:
        """Test ApiChatPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiChatPost200Response`
        """
        model = ApiChatPost200Response()
        if include_optional:
            return ApiChatPost200Response(
                response = '',
                used_rag = True,
                context_found = True,
                context = ''
            )
        else:
            return ApiChatPost200Response(
        )
        """

    def testApiChatPost200Response(self):
        """Test ApiChatPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
