# coding: utf-8

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_documents_post200_response import ApiDocumentsPost200Response

class TestApiDocumentsPost200Response(unittest.TestCase):
    """ApiDocumentsPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDocumentsPost200Response:
        """Test ApiDocumentsPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDocumentsPost200Response`
        """
        model = ApiDocumentsPost200Response()
        if include_optional:
            return ApiDocumentsPost200Response(
                message = '',
                document_id = 56,
                chunks_count = 56
            )
        else:
            return ApiDocumentsPost200Response(
        )
        """

    def testApiDocumentsPost200Response(self):
        """Test ApiDocumentsPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
