# coding: utf-8

# flake8: noqa

"""
    SAP Intern API

    API documentation for SAP internship project

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiChatPost200Response",
    "ApiChatPostRequest",
    "ApiDocumentsGet200Response",
    "ApiDocumentsGet200ResponseDocumentsInner",
    "ApiDocumentsPost200Response",
    "ApiDocumentsPostRequest",
    "ApiEmbeddingsUpdatePost200Response",
    "ApiHealthGet200Response",
]

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.api_chat_post200_response import ApiChatPost200Response as ApiChatPost200Response
from openapi_client.models.api_chat_post_request import ApiChatPostRequest as ApiChatPostRequest
from openapi_client.models.api_documents_get200_response import ApiDocumentsGet200Response as ApiDocumentsGet200Response
from openapi_client.models.api_documents_get200_response_documents_inner import ApiDocumentsGet200ResponseDocumentsInner as ApiDocumentsGet200ResponseDocumentsInner
from openapi_client.models.api_documents_post200_response import ApiDocumentsPost200Response as ApiDocumentsPost200Response
from openapi_client.models.api_documents_post_request import ApiDocumentsPostRequest as ApiDocumentsPostRequest
from openapi_client.models.api_embeddings_update_post200_response import ApiEmbeddingsUpdatePost200Response as ApiEmbeddingsUpdatePost200Response
from openapi_client.models.api_health_get200_response import ApiHealthGet200Response as ApiHealthGet200Response
